# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71a3e1ffec7faf8a8645c85dc6f24f5ff21066fd2d223b404eebae30f7bec2b66a697fbf40afb8c4a63cee5919cf6d65372b324a3ad4a896f2e434e71662dd0f

test:
  secret_key_base: 584f289aa621067f620b41ba249c9666a2558f31da3f69366f5dc411d90b3c79bc2164f5840658143555986587ccc4696d2130a9822947f4bf1fdf298ffa12b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
